### PR TITLE
Chrome unique id fix

### PR DESCRIPTION
**Pull request by itzzshirlayyy**
* Removed id #dtEntry from px-datetime-entry-cell and replaced with class variable .datetime-entry-input.
* This ensures no duplicate non-unique id error that chrome console checks for (pic below)
screen shot 2018-09-04 at 6 08 46 pm

^ this error no longer displays on the console after this fix:
screen shot 2018-09-04 at 6 45 47 pm

### CODE REVIEW

**Comment by itzzshirlayyy** [comment]
@sks please review. Thanks

**Comment by itzzshirlayyy** [comment]
@cla-bot check

**Comment by evanjd** [comment]
@itzzshirlayyy I've done a rebase + force-push to fix cla-bot - one of your commits was done with your GE e-mail which isn't tied to any github account. You may want to delete your local copy of the `chromeUniqueIdFix` and check it out again to get synchronised (if you need to make further changes).

Also updated the node-sass dependency to (hopefully) fix travis.

**Comment by itzzshirlayyy** [comment]
@evanjd Thank you so much for your promptness in resolving my issues!

**Pull request merged**
